.if !dMAINPAGE \{\
.TH "BOGUS DEBUG HEADER" 3
.so prototypes.3
.mso gproto.tmac
.\}
.SH SYNOPSIS
.ds vellipsis \[u22EE]
.PP
.B \(shinclude <pager.h>

.SS Data Types
.pt_pwb_print_line
.pt_pwb_dparms
.pt_arv
.pt_paction

.SS Setup Functions
.PP
.pt_pager_init_dparms
.pt_pager_set_margins
.pt_pager_calc_borders
.pt_pager_init
.pt_pager_cleanup

.SS Content-plotting Functions
.pt_pager_plot
.pt_pager_plot_row

.SS Pager Manipulation Functions
.pt_pager_quit
.pt_pager_activate
.pt_pager_focus_up_one
.pt_pager_focus_down_one
.pt_pager_focus_up_page
.pt_pager_focus_down_page
.pt_pager_focus_end
.pt_pager_focus_home

.SS Convenient Screen Manipulation Functions
.pt_ti_set_cursor_position
.pt_ti_hide_cursor
.pt_ti_show_cursor
