.if !dMAINPAGE \{\
.TH "BOGUS DEBUG HEADER" 3
.mso gproto.tmac
.\}
.SH SYNOPSIS
.ds vellipsis \[u22EE]
.PP
.B \(shinclude <pager.h>
.SS Data Types
.PP
.cdef_start "typedef\ int" (*pwb_print_line)
.cdef_arg int row_index
.cdef_arg int indicated
.cdef_arg int length
.cdef_arg "void\ *" data_source
.cdef_arg "void\ *" data_extra
.cdef_end_stacked
\"
.PP
.B typedef struct
.br
.cdef_start "" "display_parameters"  {} ;
.cdef_arg int index_row_top
.cdef_arg int index_row_focus
.cdef_arg "void\ *" data_source
.cdef_arg int row_count
.cdef_arg pwb_print_line printer
.cdef_arg "void\ *" data_extra
.\" .cdef_arg \\*[vellipsis] ""
.cdef_arg  int margin_top
.cdef_arg  int margin_right
.cdef_arg  int margin_bottom
.cdef_arg  int margin_left
.cdef_arg int line_top
.cdef_arg int line_bottom
.cdef_arg int line_count
.cdef_arg int chars_left
.cdef_arg int chars_count
.cdef_end_stacked DPARMS
.PP
.cdef_start "typedef enum" ""  {} ,
.cdef_arg ARV_CONTINUE =\ 0
.cdef_arg ARV_REPLOT_DATA ""
.cdef_arg ARV_EXIT ""
.cdef_end_stacked ARV
.PP
.cdef_start "typedef\ ARV" (*PACTION)
.cdef_arg DPARMS* parms
.cdef_end

.SS Setup Functions
.PP
.cdef_start void pager_init_dparms () ,
.cdef_arg "DPARMS\ *" dparms
.cdef_arg "void\ *" data_source
.cdef_arg int row_count
.cdef_arg pwb_print_line printer
.cdef_end
.\"
.cdef_start void pager_set_margins
.cdef_arg "DPARMS\ *" params
.cdef_arg int top
.cdef_arg int right
.cdef_arg int bottom
.cdef_arg int left
.cdef_end
.\"
.cdef_start void pager_calc_borders
.cdef_arg "DPARMS\ *" params
.cdef_end
.\"
.cdef_start void pager_init
.cdef_arg void ""
.cdef_end
.\"
.cdef_start void pager_cleanup
.cdef_arg void ""
.cdef_end
'\"
.SS Content-plotting Functions
.cdef_start void pager_plot
.cdef_arg "DPARMS\ *" parms
.cdef_end
'\"
.cdef_start void pager_plot_row
.cdef_arg "DPARMS\ *" parms
.cdef_end

.SS Pager Manipulation Functions

.cdef_start ARV pager_quit ()
.cdef_arg "DPARMS\ *" parms
.cdef_end
'\"
.cdef_start ARV pager_activate ()
.cdef_arg "DPARMS\ *" parms
.cdef_end
'\"
.cdef_start ARV pager_focus_up_one ()
.cdef_arg "DPARMS\ *" parms
.cdef_end
'\"
.cdef_start ARV pager_focus_down_one ()
.cdef_arg "DPARMS\ *" parms
.cdef_end
'\"
.cdef_start ARV pager_focus_up_page ()
.cdef_arg "DPARMS\ *" parms
.cdef_end
'\"
.cdef_start ARV pager_focus_down_page ()
.cdef_arg "DPARMS\ *" parms
.cdef_end
'\"
.cdef_start ARV pager_focus_end ()
.cdef_arg "DPARMS\ *" parms
.cdef_end
'\"
.cdef_start ARV pager_focus_home ()
.cdef_arg "DPARMS\ *" parms
.cdef_end

.SS Convenient Screen Manipulation Functions
.cdef_start void ti_set_cursor_position
.cdef_arg int row
.cdef_arg int col
.cdef_end
'\"
.cdef_start ti_hide_cursor
.cdef_end
'\"
.cdef_start ti_show_cursor
.cdef_end
