.TH pager 3 2023-12-21
.mso gproto.tmac
.nr include_flag 1
.so fork.tmac
.so pager.3.d/prototypes.3
.SH NAME
.PP
.B pager
\- C library for presenting a simple pager
.SH LIBRARY
.PP
link with
.B -lpager -ltinfo
.so pager.3.d/prototypes.3
.so pager.3.d/synopsis.3
.so pager.3.d/description.3
.SH DATA TYPES
.so pager.3.d/struct_dparms.3
.SH FUNCTIONS
.PP
Non-obvious functions will be documented here when time allows.
.so pager.3.d/pager_set_focus.3
